package com.simulationFrameworkDT.simulation.event;

public enum EventType {
	
	ARCHIVO_LOG_DEL_VEHICULO_CORRUPTO,
	POSICIONAMIENTO_GPS,
	RECONOCIMIENTO_DE_PUNTO_DE_PARADA,
	APERTURA_DE_PUERTAS,
	SOBREESCRITURA_DEL_ARCHIVO_LOG,
	CIERRE_DE_PUERTAS,
	DESCONEXION_DEL_MODULO_GPRS,
	IVU_BOX_APAGADO_IGNICION,
	REINICIO_IVU_BOX_FUENTE_PODER,
	REINICIO_IVU_BOX_OPERADOR,
	RETORNO_DE_REINICIO;
}
	